
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Jun 28 2026 12:52:47 -03 (Jun 28 2026 15:52:47 UTC)

// Verification Directory fv/spi_top 

module spi_top(clk, rst, write_en, read_en, addr, write_data,
     read_data, spi_sclk, spi_mosi, spi_miso, spi_cs_n);
  input clk, rst, write_en, read_en, spi_miso;
  input [2:0] addr;
  input [7:0] write_data;
  output [7:0] read_data;
  output spi_sclk, spi_mosi, spi_cs_n;
  wire clk, rst, write_en, read_en, spi_miso;
  wire [2:0] addr;
  wire [7:0] write_data;
  wire [7:0] read_data;
  wire spi_sclk, spi_mosi, spi_cs_n;
  wire [7:0] tx_data;
  wire [7:0] rx_data;
  wire [15:0] clk_div;
  wire [7:0] u_regs_reg_rx_data;
  wire [1:0] spi_mode;
  wire [7:0] u_regs_reg_ctrl;
  wire [15:0] u_clk_gen_counter;
  wire [1:0] u_fsm_state;
  wire bit_cnt_max, load_en, n_0, n_1, n_2, n_3, n_4, n_5;
  wire n_6, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_44, n_45, n_46;
  wire n_47, n_48, n_49, n_50, n_51, n_52, n_53, n_54;
  wire n_55, n_56, n_57, n_58, n_59, n_60, n_61, n_62;
  wire n_63, n_64, n_65, n_66, n_67, n_68, n_69, n_70;
  wire n_71, n_72, n_73, n_74, n_75, n_76, n_77, n_78;
  wire n_79, n_80, n_81, n_82, n_83, n_84, n_85, n_86;
  wire n_87, n_88, n_89, n_90, n_91, n_92, n_93, n_94;
  wire n_95, n_96, n_97, n_98, n_99, n_100, n_101, n_102;
  wire n_103, n_104, n_105, n_106, n_107, n_108, n_109, n_110;
  wire n_111, n_112, n_113, n_114, n_115, n_116, n_117, n_118;
  wire n_119, n_120, n_121, n_122, n_123, n_124, n_125, n_126;
  wire n_127, n_128, n_129, n_130, n_131, n_132, n_133, n_134;
  wire n_135, n_136, n_137, n_138, n_139, n_140, n_141, n_142;
  wire n_143, n_144, n_145, n_146, n_147, n_148, n_149, n_150;
  wire n_151, n_152, n_153, n_154, n_155, n_156, n_157, n_158;
  wire n_159, n_160, n_161, n_162, n_163, n_164, n_165, n_166;
  wire n_167, n_168, n_169, n_170, n_171, n_172, n_173, n_174;
  wire n_175, n_176, n_177, n_178, n_179, n_180, n_181, n_182;
  wire n_183, n_184, n_185, n_186, n_187, n_188, n_189, n_190;
  wire n_191, n_192, n_193, n_194, n_195, n_196, n_197, n_198;
  wire n_199, n_200, n_202, n_203, n_204, n_205, n_206, n_207;
  wire n_208, n_209, n_210, n_211, n_212, n_213, n_214, n_215;
  wire n_216, n_217, n_218, n_219, n_220, n_221, n_222, n_223;
  wire n_224, n_225, n_227, n_228, n_229, n_230, n_231, n_232;
  wire n_233, n_234, n_235, n_237, n_238, n_239, n_240, n_241;
  wire n_242, n_243, n_244, n_245, n_246, n_247, n_248, n_250;
  wire n_251, n_252, n_253, n_254, n_257, n_258, n_259, n_260;
  wire n_261, n_262, n_263, n_264, n_265, n_266, n_267, n_268;
  wire n_269, n_270, n_271, n_272, n_273, n_274, n_275, n_276;
  wire n_277, n_278, n_279, n_280, n_281, n_282, n_283, n_284;
  wire n_285, n_286, n_287, n_288, n_289, n_290, n_291, n_292;
  wire n_293, n_294, n_295, n_296, n_297, n_298, n_299, n_300;
  wire n_301, n_302, n_303, n_304, n_305, n_306, n_307, n_308;
  wire n_309, n_310, n_311, n_312, n_313, n_314, n_315, n_316;
  wire n_317, n_318, n_319, n_320, n_321, n_322, n_323, n_324;
  wire n_325, n_326, n_327, n_328, n_329, n_330, n_331, n_332;
  wire n_333, n_335, n_336, n_338, n_339, n_340, n_341, n_342;
  wire n_343, n_344, n_345, n_346, n_347, n_348, n_351, n_360;
  wire n_361, n_362, n_363, n_391, n_392, sample_edge, shift_edge,
       shift_en;
  wire start, u_clk_gen_n_76, u_clk_gen_n_237, u_clk_gen_sclk_int,
       u_fsm_n_73, u_regs_n_142, u_regs_reg_done_latch;
  spi_data u_datapath(.clk (clk), .rst (rst), .tx_data (tx_data),
       .rx_data (rx_data), .load_en (load_en), .shift_en (shift_en),
       .bit_cnt_max (bit_cnt_max), .sample_edge (sample_edge),
       .shift_edge (shift_edge), .spi_mosi (spi_mosi), .spi_miso
       (spi_miso));
  INVX1 g1808(.A (u_fsm_n_73), .Y (shift_en));
  INVX1 g1809(.A (n_361), .Y (n_252));
  DFFSR u_clk_gen_sample_edge_reg(.R (rst), .S (1'b1), .CLK (clk), .D
       (n_347), .Q (sample_edge));
  DFFSR u_clk_gen_shift_edge_reg(.R (rst), .S (1'b1), .CLK (clk), .D
       (n_200), .Q (shift_edge));
  DFFSR u_regs_start_reg(.R (rst), .S (1'b1), .CLK (clk), .D (n_319),
       .Q (n_348));
  INVX1 g3908(.A (n_347), .Y (u_clk_gen_n_237));
  NOR3X1 g3909__2398(.A (u_clk_gen_sclk_int), .B (u_fsm_n_73), .C
       (u_clk_gen_n_76), .Y (n_347));
  NOR2X1 g3910__5107(.A (n_259), .B (u_clk_gen_n_76), .Y (n_346));
  OR2X1 g3911__6260(.A (n_214), .B (n_318), .Y (u_clk_gen_n_76));
  NAND3X1 g3912__4319(.A (n_254), .B (n_297), .C (n_344), .Y (n_345));
  NOR3X1 g3913__8428(.A (n_312), .B (n_333), .C (n_225), .Y (n_344));
  NAND3X1 g3914__5526(.A (n_317), .B (n_311), .C (n_342), .Y (n_343));
  NOR3X1 g3915__6783(.A (n_308), .B (n_309), .C (n_224), .Y (n_342));
  NAND3X1 g3916__3680(.A (n_298), .B (n_295), .C (n_221), .Y (n_341));
  AOI21X1 g3917__1617(.A (n_290), .B (n_292), .C (n_213), .Y (n_340));
  NAND3X1 g3918__2802(.A (n_306), .B (n_307), .C (n_338), .Y (n_339));
  NOR3X1 g3919__1705(.A (n_305), .B (n_304), .C (n_392), .Y (n_338));
  NAND3X1 g3920__5122(.A (n_215), .B (n_220), .C (n_335), .Y
       (read_data[1]));
  NAND3X1 g3921__8246(.A (n_217), .B (n_219), .C (n_336), .Y
       (read_data[0]));
  NAND3X1 g3922__7098(.A (n_216), .B (n_218), .C (n_222), .Y
       (read_data[2]));
  NAND2X1 g3924__1881(.A (n_208), .B (n_202), .Y (read_data[7]));
  NAND2X1 g3925__5115(.A (n_207), .B (n_198), .Y (read_data[5]));
  NAND2X1 g3927__7482(.A (n_206), .B (n_196), .Y (read_data[6]));
  NAND2X1 g3928__4733(.A (n_204), .B (n_203), .Y (read_data[4]));
  AND2X1 g3929__6161(.A (n_209), .B (n_211), .Y (n_336));
  AND2X1 g3930__9315(.A (n_210), .B (n_212), .Y (n_335));
  NAND2X1 g3931__9945(.A (n_205), .B (n_199), .Y (read_data[3]));
  OAI21X1 g3933__2346(.A (n_293), .B (n_287), .C (n_197), .Y (n_333));
  AOI22X1 g3934__1666(.A (n_262), .B (tx_data[0]), .C (clk_div[8]), .D
       (n_284), .Y (n_332));
  AOI22X1 g3935__7410(.A (n_262), .B (tx_data[7]), .C
       (u_regs_reg_rx_data[7]), .D (n_261), .Y (n_331));
  AOI22X1 g3936__6417(.A (n_263), .B (clk_div[3]), .C (clk_div[11]), .D
       (n_284), .Y (n_330));
  AOI22X1 g3937__5477(.A (n_263), .B (clk_div[6]), .C (clk_div[14]), .D
       (n_284), .Y (n_329));
  AOI22X1 g3938__2398(.A (n_263), .B (clk_div[2]), .C
       (u_regs_reg_rx_data[2]), .D (n_261), .Y (n_328));
  AOI22X1 g3939__5107(.A (n_263), .B (clk_div[7]), .C (clk_div[15]), .D
       (n_284), .Y (n_327));
  AOI22X1 g3940__6260(.A (n_262), .B (tx_data[5]), .C
       (u_regs_reg_rx_data[5]), .D (n_261), .Y (n_326));
  AOI22X1 g3941__4319(.A (n_263), .B (clk_div[5]), .C (clk_div[13]), .D
       (n_284), .Y (n_325));
  AOI22X1 g3942__8428(.A (n_285), .B (spi_mode[1]), .C (tx_data[2]), .D
       (n_262), .Y (n_324));
  AOI22X1 g3943__5526(.A (n_287), .B (n_293), .C (n_286), .D (n_288),
       .Y (n_323));
  AOI22X1 g3944__6783(.A (n_264), .B (u_regs_reg_done_latch), .C
       (tx_data[1]), .D (n_262), .Y (n_322));
  AOI22X1 g3945__3680(.A (n_262), .B (tx_data[4]), .C
       (u_regs_reg_rx_data[4]), .D (n_261), .Y (n_321));
  AOI22X1 g3946__1617(.A (n_263), .B (clk_div[1]), .C (clk_div[9]), .D
       (n_284), .Y (n_320));
  NOR3X1 g3947__2802(.A (n_8), .B (n_223), .C (n_362), .Y (n_319));
  INVX1 g3948(.A (n_303), .Y (n_318));
  XOR2X1 g3949__1705(.A (n_266), .B (n_272), .Y (n_317));
  AOI22X1 g3950__5122(.A (n_264), .B (n_8), .C (u_regs_reg_ctrl[0]), .D
       (n_285), .Y (n_316));
  AOI22X1 g3951__8246(.A (n_262), .B (tx_data[6]), .C
       (u_regs_reg_rx_data[6]), .D (n_261), .Y (n_315));
  AOI22X1 g3952__7098(.A (n_262), .B (tx_data[3]), .C
       (u_regs_reg_rx_data[3]), .D (n_261), .Y (n_314));
  XNOR2X1 g3953__6131(.A (n_275), .B (n_282), .Y (n_313));
  XNOR2X1 g3954__1881(.A (n_268), .B (n_265), .Y (n_312));
  XOR2X1 g3955__5115(.A (n_271), .B (n_267), .Y (n_311));
  AOI22X1 g3956__7482(.A (n_263), .B (clk_div[4]), .C (clk_div[12]), .D
       (n_284), .Y (n_310));
  XNOR2X1 g3957__4733(.A (n_277), .B (n_270), .Y (n_309));
  XNOR2X1 g3958__6161(.A (n_273), .B (n_253), .Y (n_308));
  XOR2X1 g3959__9315(.A (n_279), .B (n_276), .Y (n_307));
  XOR2X1 g3960__9945(.A (n_274), .B (n_280), .Y (n_306));
  XNOR2X1 g3961__2883(.A (n_281), .B (n_278), .Y (n_305));
  XNOR2X1 g3962__2346(.A (n_283), .B (n_269), .Y (n_304));
  MUX2X1 g3963__1666(.A (u_clk_gen_counter[0]), .B (n_294), .S
       (clk_div[0]), .Y (n_303));
  NAND2X1 g3964__7410(.A (u_regs_reg_ctrl[1]), .B (n_285), .Y (n_302));
  NAND2X1 g3965__6417(.A (clk_div[0]), .B (n_263), .Y (n_301));
  NAND2X1 g3966__5477(.A (clk_div[10]), .B (n_284), .Y (n_300));
  NAND2X1 g3967__2398(.A (u_regs_reg_rx_data[1]), .B (n_261), .Y
       (n_299));
  OR2X1 g3968__5107(.A (n_292), .B (n_290), .Y (n_298));
  OR2X1 g3969__6260(.A (n_294), .B (u_clk_gen_counter[0]), .Y (n_297));
  NAND2X1 g3970__4319(.A (u_regs_reg_rx_data[0]), .B (n_261), .Y
       (n_296));
  OR2X1 g3971__8428(.A (n_288), .B (n_286), .Y (n_295));
  XNOR2X1 g3972__5526(.A (n_259), .B (spi_mode[1]), .Y (spi_sclk));
  HAX1 g3973__6783(.A (u_clk_gen_counter[1]), .B (n_228), .YC (n_293),
       .YS (n_294));
  HAX1 g3974__3680(.A (u_clk_gen_counter[4]), .B (n_232), .YC (n_282),
       .YS (n_283));
  HAX1 g3975__1617(.A (n_237), .B (u_clk_gen_counter[13]), .YC (n_280),
       .YS (n_281));
  HAX1 g3976__2802(.A (u_clk_gen_counter[12]), .B (n_230), .YC (n_278),
       .YS (n_279));
  HAX1 g3977__1705(.A (u_clk_gen_counter[11]), .B (n_235), .YC (n_276),
       .YS (n_277));
  HAX1 g3978__5122(.A (u_clk_gen_counter[6]), .B (n_238), .YC (n_291),
       .YS (n_292));
  HAX1 g3979__8246(.A (u_clk_gen_counter[5]), .B (n_227), .YC (n_290),
       .YS (n_275));
  HAX1 g3980__7098(.A (u_clk_gen_counter[14]), .B (n_246), .YC (n_273),
       .YS (n_274));
  HAX1 g3981__6131(.A (u_clk_gen_counter[7]), .B (n_241), .YC (n_272),
       .YS (n_289));
  HAX1 g3982__1881(.A (u_clk_gen_counter[10]), .B (n_247), .YC (n_270),
       .YS (n_271));
  HAX1 g3983__5115(.A (u_clk_gen_counter[3]), .B (n_245), .YC (n_269),
       .YS (n_288));
  HAX1 g3984__7482(.A (u_clk_gen_counter[2]), .B (n_244), .YC (n_286),
       .YS (n_287));
  HAX1 g3985__4733(.A (u_clk_gen_counter[9]), .B (n_243), .YC (n_267),
       .YS (n_268));
  HAX1 g3986__6161(.A (u_clk_gen_counter[8]), .B (n_242), .YC (n_265),
       .YS (n_266));
  OR2X1 g3987__9315(.A (n_360), .B (addr[2]), .Y (n_362));
  AND2X1 g3988__9945(.A (n_257), .B (n_233), .Y (n_285));
  AND2X1 g3989__2883(.A (n_260), .B (addr[1]), .Y (n_284));
  INVX1 g3990(.A (n_264), .Y (u_regs_n_142));
  AND2X1 g3991__2346(.A (n_260), .B (n_233), .Y (n_264));
  AND2X1 g3992__1666(.A (n_257), .B (addr[1]), .Y (n_263));
  NOR3X1 g3993__7410(.A (addr[0]), .B (addr[1]), .C (n_251), .Y
       (n_262));
  NOR3X1 g3994__6417(.A (addr[1]), .B (n_234), .C (n_251), .Y (n_261));
  AND2X1 g3995__5477(.A (n_252), .B (read_en), .Y (n_260));
  OR2X1 g3996__2398(.A (u_fsm_n_73), .B (n_6), .Y (n_259));
  INVX1 g3997(.A (n_8), .Y (spi_cs_n));
  NAND3X1 g3998__5107(.A (write_en), .B (n_234), .C (n_233), .Y
       (n_258));
  NOR3X1 g3999__6260(.A (addr[2]), .B (addr[0]), .C (n_231), .Y
       (n_257));
  OR2X1 g4000__4319(.A (n_11), .B (n_351), .Y (n_8));
  INVX1 g4001(.A (u_fsm_n_73), .Y (n_11));
  OR2X1 g4002__8428(.A (n_248), .B (clk_div[15]), .Y (n_254));
  AND2X1 g4003__5526(.A (n_229), .B (u_fsm_state[0]), .Y (n_351));
  OR2X1 g4004__6783(.A (n_239), .B (u_clk_gen_counter[15]), .Y (n_253));
  OR2X1 g4005__3680(.A (n_229), .B (u_fsm_state[0]), .Y (u_fsm_n_73));
  NAND2X1 g4007__1617(.A (write_data[0]), .B (write_data[3]), .Y
       (n_250));
  OR2X1 g4008__2802(.A (n_229), .B (n_240), .Y (n_363));
  OR2X1 g4009__1705(.A (n_234), .B (addr[2]), .Y (n_361));
  OR2X1 g4010__5122(.A (n_231), .B (n_10), .Y (n_251));
  INVX1 g4012(.A (u_clk_gen_counter[15]), .Y (n_248));
  INVX1 g4013(.A (clk_div[10]), .Y (n_247));
  INVX1 g4014(.A (clk_div[14]), .Y (n_246));
  INVX1 g4015(.A (clk_div[3]), .Y (n_245));
  INVX1 g4016(.A (clk_div[2]), .Y (n_244));
  INVX1 g4017(.A (clk_div[9]), .Y (n_243));
  INVX1 g4018(.A (clk_div[8]), .Y (n_242));
  INVX1 g4019(.A (clk_div[7]), .Y (n_241));
  INVX1 g4020(.A (u_fsm_state[0]), .Y (n_240));
  INVX1 g4021(.A (clk_div[15]), .Y (n_239));
  INVX1 g4022(.A (clk_div[6]), .Y (n_238));
  INVX1 g4023(.A (clk_div[13]), .Y (n_237));
  INVX1 g4024(.A (addr[2]), .Y (n_10));
  INVX1 g4025(.A (clk_div[11]), .Y (n_235));
  INVX1 g4026(.A (addr[0]), .Y (n_234));
  INVX1 g4027(.A (addr[1]), .Y (n_233));
  INVX1 g4028(.A (clk_div[4]), .Y (n_232));
  INVX1 g4029(.A (read_en), .Y (n_231));
  INVX1 g4030(.A (clk_div[12]), .Y (n_230));
  INVX1 g4031(.A (u_fsm_state[1]), .Y (n_229));
  INVX1 g4032(.A (clk_div[1]), .Y (n_228));
  INVX1 g4033(.A (clk_div[5]), .Y (n_227));
  BUFX2 drc_bufs(.A (n_348), .Y (start));
  BUFX2 drc_bufs4038(.A (n_343), .Y (n_225));
  BUFX2 drc_bufs4039(.A (n_341), .Y (n_224));
  BUFX2 drc_bufs4040(.A (n_250), .Y (n_223));
  BUFX2 drc_bufs4041(.A (n_328), .Y (n_222));
  BUFX2 drc_bufs4042(.A (n_340), .Y (n_221));
  BUFX2 drc_bufs4043(.A (n_302), .Y (n_220));
  BUFX2 drc_bufs4044(.A (n_301), .Y (n_219));
  BUFX2 drc_bufs4045(.A (n_300), .Y (n_218));
  BUFX2 drc_bufs4046(.A (n_332), .Y (n_217));
  BUFX2 drc_bufs4047(.A (n_324), .Y (n_216));
  BUFX2 drc_bufs4048(.A (n_322), .Y (n_215));
  BUFX2 drc_bufs4049(.A (n_345), .Y (n_214));
  BUFX2 drc_bufs4050(.A (n_339), .Y (n_213));
  BUFX2 drc_bufs4051(.A (n_299), .Y (n_212));
  BUFX2 drc_bufs4052(.A (n_296), .Y (n_211));
  BUFX2 drc_bufs4053(.A (n_320), .Y (n_210));
  BUFX2 drc_bufs4054(.A (n_316), .Y (n_209));
  BUFX2 drc_bufs4055(.A (n_331), .Y (n_208));
  BUFX2 drc_bufs4056(.A (n_326), .Y (n_207));
  BUFX2 drc_bufs4057(.A (n_315), .Y (n_206));
  BUFX2 drc_bufs4058(.A (n_314), .Y (n_205));
  BUFX2 drc_bufs4059(.A (n_321), .Y (n_204));
  BUFX2 drc_bufs4060(.A (n_310), .Y (n_203));
  BUFX2 drc_bufs4061(.A (n_327), .Y (n_202));
  BUFX2 drc_bufs4063(.A (n_346), .Y (n_200));
  BUFX2 drc_bufs4064(.A (n_330), .Y (n_199));
  BUFX2 drc_bufs4065(.A (n_325), .Y (n_198));
  BUFX2 drc_bufs4066(.A (n_323), .Y (n_197));
  BUFX2 drc_bufs4067(.A (n_329), .Y (n_196));
  BUFX2 drc_bufs4068(.A (n_258), .Y (n_360));
  DFFSR \u_clk_gen_counter_reg[0] (.R (rst), .S (1'b1), .CLK (clk), .D
       (n_37), .Q (n_141));
  DFFSR \u_clk_gen_counter_reg[1] (.R (rst), .S (1'b1), .CLK (clk), .D
       (n_65), .Q (n_142));
  DFFSR \u_clk_gen_counter_reg[2] (.R (rst), .S (1'b1), .CLK (clk), .D
       (n_102), .Q (n_143));
  DFFSR \u_clk_gen_counter_reg[3] (.R (rst), .S (1'b1), .CLK (clk), .D
       (n_105), .Q (n_144));
  DFFSR \u_clk_gen_counter_reg[4] (.R (rst), .S (1'b1), .CLK (clk), .D
       (n_108), .Q (n_145));
  DFFSR \u_clk_gen_counter_reg[5] (.R (rst), .S (1'b1), .CLK (clk), .D
       (n_111), .Q (n_146));
  DFFSR \u_clk_gen_counter_reg[6] (.R (rst), .S (1'b1), .CLK (clk), .D
       (n_114), .Q (n_147));
  DFFSR \u_clk_gen_counter_reg[7] (.R (rst), .S (1'b1), .CLK (clk), .D
       (n_117), .Q (n_148));
  DFFSR \u_clk_gen_counter_reg[8] (.R (rst), .S (1'b1), .CLK (clk), .D
       (n_120), .Q (n_149));
  DFFSR \u_clk_gen_counter_reg[9] (.R (rst), .S (1'b1), .CLK (clk), .D
       (n_123), .Q (n_150));
  DFFSR \u_clk_gen_counter_reg[10] (.R (rst), .S (1'b1), .CLK (clk), .D
       (n_126), .Q (n_151));
  DFFSR \u_clk_gen_counter_reg[11] (.R (rst), .S (1'b1), .CLK (clk), .D
       (n_129), .Q (n_152));
  DFFSR \u_clk_gen_counter_reg[12] (.R (rst), .S (1'b1), .CLK (clk), .D
       (n_132), .Q (n_153));
  DFFSR \u_clk_gen_counter_reg[13] (.R (rst), .S (1'b1), .CLK (clk), .D
       (n_135), .Q (n_154));
  DFFSR \u_clk_gen_counter_reg[14] (.R (rst), .S (1'b1), .CLK (clk), .D
       (n_138), .Q (n_155));
  DFFSR \u_clk_gen_counter_reg[15] (.R (rst), .S (1'b1), .CLK (clk), .D
       (n_140), .Q (n_156));
  DFFSR u_clk_gen_sclk_int_reg(.R (rst), .S (1'b1), .CLK (clk), .D
       (n_50), .Q (n_157));
  DFFSR \u_fsm_state_reg[0] (.R (rst), .S (1'b1), .CLK (clk), .D (n_0),
       .Q (n_158));
  DFFSR \u_fsm_state_reg[1] (.R (rst), .S (1'b1), .CLK (clk), .D (n_8),
       .Q (n_187));
  DFFSR \u_regs_reg_clk_hi_reg[0] (.R (rst), .S (1'b1), .CLK (clk), .D
       (n_83), .Q (n_159));
  DFFSR \u_regs_reg_clk_hi_reg[1] (.R (rst), .S (1'b1), .CLK (clk), .D
       (n_81), .Q (n_160));
  DFFSR \u_regs_reg_clk_hi_reg[2] (.R (rst), .S (1'b1), .CLK (clk), .D
       (n_82), .Q (n_161));
  DFFSR \u_regs_reg_clk_hi_reg[3] (.R (rst), .S (1'b1), .CLK (clk), .D
       (n_75), .Q (n_162));
  DFFSR \u_regs_reg_clk_hi_reg[4] (.R (rst), .S (1'b1), .CLK (clk), .D
       (n_76), .Q (n_163));
  DFFSR \u_regs_reg_clk_hi_reg[5] (.R (rst), .S (1'b1), .CLK (clk), .D
       (n_77), .Q (n_164));
  DFFSR \u_regs_reg_clk_hi_reg[6] (.R (rst), .S (1'b1), .CLK (clk), .D
       (n_74), .Q (n_165));
  DFFSR \u_regs_reg_clk_hi_reg[7] (.R (rst), .S (1'b1), .CLK (clk), .D
       (n_73), .Q (n_166));
  DFFSR \u_regs_reg_clk_lo_reg[0] (.R (rst), .S (1'b1), .CLK (clk), .D
       (n_98), .Q (n_167));
  DFFSR \u_regs_reg_clk_lo_reg[1] (.R (rst), .S (1'b1), .CLK (clk), .D
       (n_97), .Q (n_168));
  DFFSR \u_regs_reg_clk_lo_reg[2] (.R (1'b1), .S (rst), .CLK (clk), .D
       (n_96), .Q (n_169));
  DFFSR \u_regs_reg_clk_lo_reg[3] (.R (rst), .S (1'b1), .CLK (clk), .D
       (n_99), .Q (n_170));
  DFFSR \u_regs_reg_clk_lo_reg[4] (.R (rst), .S (1'b1), .CLK (clk), .D
       (n_94), .Q (n_171));
  DFFSR \u_regs_reg_clk_lo_reg[5] (.R (rst), .S (1'b1), .CLK (clk), .D
       (n_93), .Q (n_172));
  DFFSR \u_regs_reg_clk_lo_reg[6] (.R (rst), .S (1'b1), .CLK (clk), .D
       (n_92), .Q (n_173));
  DFFSR \u_regs_reg_clk_lo_reg[7] (.R (rst), .S (1'b1), .CLK (clk), .D
       (n_95), .Q (n_174));
  DFFSR \u_regs_reg_ctrl_reg[0] (.R (rst), .S (1'b1), .CLK (clk), .D
       (n_30), .Q (n_175));
  DFFSR \u_regs_reg_ctrl_reg[1] (.R (rst), .S (1'b1), .CLK (clk), .D
       (n_25), .Q (n_176));
  DFFSR \u_regs_reg_ctrl_reg[2] (.R (rst), .S (1'b1), .CLK (clk), .D
       (n_24), .Q (n_177));
  DFFSR u_regs_reg_done_latch_reg(.R (rst), .S (1'b1), .CLK (clk), .D
       (n_66), .Q (n_178));
  DFFSR \u_regs_reg_rx_data_reg[0] (.R (rst), .S (1'b1), .CLK (clk), .D
       (n_42), .Q (n_179));
  DFFSR \u_regs_reg_rx_data_reg[1] (.R (rst), .S (1'b1), .CLK (clk), .D
       (n_40), .Q (n_180));
  DFFSR \u_regs_reg_rx_data_reg[2] (.R (rst), .S (1'b1), .CLK (clk), .D
       (n_39), .Q (n_181));
  DFFSR \u_regs_reg_rx_data_reg[3] (.R (rst), .S (1'b1), .CLK (clk), .D
       (n_41), .Q (n_182));
  DFFSR \u_regs_reg_rx_data_reg[4] (.R (rst), .S (1'b1), .CLK (clk), .D
       (n_26), .Q (n_183));
  DFFSR \u_regs_reg_rx_data_reg[5] (.R (rst), .S (1'b1), .CLK (clk), .D
       (n_29), .Q (n_184));
  DFFSR \u_regs_reg_rx_data_reg[6] (.R (rst), .S (1'b1), .CLK (clk), .D
       (n_28), .Q (n_185));
  DFFSR \u_regs_reg_rx_data_reg[7] (.R (rst), .S (1'b1), .CLK (clk), .D
       (n_27), .Q (n_186));
  DFFSR \u_regs_reg_tx_data_reg[0] (.R (rst), .S (1'b1), .CLK (clk), .D
       (n_61), .Q (n_195));
  DFFSR \u_regs_reg_tx_data_reg[1] (.R (rst), .S (1'b1), .CLK (clk), .D
       (n_60), .Q (n_194));
  DFFSR \u_regs_reg_tx_data_reg[2] (.R (rst), .S (1'b1), .CLK (clk), .D
       (n_62), .Q (n_193));
  DFFSR \u_regs_reg_tx_data_reg[3] (.R (rst), .S (1'b1), .CLK (clk), .D
       (n_58), .Q (n_192));
  DFFSR \u_regs_reg_tx_data_reg[4] (.R (rst), .S (1'b1), .CLK (clk), .D
       (n_57), .Q (n_191));
  DFFSR \u_regs_reg_tx_data_reg[5] (.R (rst), .S (1'b1), .CLK (clk), .D
       (n_56), .Q (n_190));
  DFFSR \u_regs_reg_tx_data_reg[6] (.R (rst), .S (1'b1), .CLK (clk), .D
       (n_55), .Q (n_189));
  DFFSR \u_regs_reg_tx_data_reg[7] (.R (rst), .S (1'b1), .CLK (clk), .D
       (n_59), .Q (n_188));
  AND2X1 g2345__8246(.A (n_139), .B (n_14), .Y (n_140));
  XOR2X1 g2347__7098(.A (n_136), .B (u_clk_gen_counter[15]), .Y
       (n_139));
  AND2X1 g2348__6131(.A (n_137), .B (n_14), .Y (n_138));
  HAX1 g2349__1881(.A (u_clk_gen_counter[14]), .B (n_133), .YC (n_136),
       .YS (n_137));
  AND2X1 g2351__5115(.A (n_134), .B (n_14), .Y (n_135));
  HAX1 g2352__7482(.A (u_clk_gen_counter[13]), .B (n_130), .YC (n_133),
       .YS (n_134));
  AND2X1 g2354__4733(.A (n_131), .B (n_14), .Y (n_132));
  HAX1 g2355__6161(.A (u_clk_gen_counter[12]), .B (n_127), .YC (n_130),
       .YS (n_131));
  AND2X1 g2357__9315(.A (n_14), .B (n_128), .Y (n_129));
  HAX1 g2358__9945(.A (u_clk_gen_counter[11]), .B (n_124), .YC (n_127),
       .YS (n_128));
  AND2X1 g2360__2883(.A (n_14), .B (n_125), .Y (n_126));
  HAX1 g2361__2346(.A (u_clk_gen_counter[10]), .B (n_121), .YC (n_124),
       .YS (n_125));
  AND2X1 g2363__1666(.A (n_14), .B (n_122), .Y (n_123));
  HAX1 g2364__7410(.A (u_clk_gen_counter[9]), .B (n_118), .YC (n_121),
       .YS (n_122));
  AND2X1 g2366__6417(.A (n_14), .B (n_119), .Y (n_120));
  HAX1 g2367__5477(.A (u_clk_gen_counter[8]), .B (n_115), .YC (n_118),
       .YS (n_119));
  AND2X1 g2369__2398(.A (n_14), .B (n_116), .Y (n_117));
  HAX1 g2370__5107(.A (u_clk_gen_counter[7]), .B (n_112), .YC (n_115),
       .YS (n_116));
  AND2X1 g2372__6260(.A (n_14), .B (n_113), .Y (n_114));
  HAX1 g2373__4319(.A (u_clk_gen_counter[6]), .B (n_109), .YC (n_112),
       .YS (n_113));
  AND2X1 g2375__8428(.A (n_14), .B (n_110), .Y (n_111));
  HAX1 g2376__5526(.A (u_clk_gen_counter[5]), .B (n_106), .YC (n_109),
       .YS (n_110));
  AND2X1 g2378__6783(.A (n_14), .B (n_107), .Y (n_108));
  HAX1 g2379__3680(.A (u_clk_gen_counter[4]), .B (n_103), .YC (n_106),
       .YS (n_107));
  AND2X1 g2381__1617(.A (n_14), .B (n_104), .Y (n_105));
  HAX1 g2382__2802(.A (u_clk_gen_counter[3]), .B (n_100), .YC (n_103),
       .YS (n_104));
  AND2X1 g2388__1705(.A (n_14), .B (n_101), .Y (n_102));
  HAX1 g2393__5122(.A (u_clk_gen_counter[2]), .B (n_63), .YC (n_100),
       .YS (n_101));
  INVX1 g2402(.A (n_91), .Y (n_99));
  INVX1 g2403(.A (n_90), .Y (n_98));
  INVX1 g2404(.A (n_89), .Y (n_97));
  INVX1 g2405(.A (n_88), .Y (n_96));
  INVX1 g2406(.A (n_87), .Y (n_95));
  INVX1 g2407(.A (n_86), .Y (n_94));
  INVX1 g2408(.A (n_85), .Y (n_93));
  INVX1 g2409(.A (n_84), .Y (n_92));
  MUX2X1 g2410__8246(.A (clk_div[3]), .B (write_data[3]), .S (n_67), .Y
       (n_91));
  MUX2X1 g2411__7098(.A (clk_div[0]), .B (write_data[0]), .S (n_67), .Y
       (n_90));
  MUX2X1 g2412__6131(.A (clk_div[1]), .B (write_data[1]), .S (n_67), .Y
       (n_89));
  MUX2X1 g2413__1881(.A (clk_div[2]), .B (write_data[2]), .S (n_67), .Y
       (n_88));
  MUX2X1 g2414__5115(.A (clk_div[7]), .B (write_data[7]), .S (n_67), .Y
       (n_87));
  MUX2X1 g2415__7482(.A (clk_div[4]), .B (write_data[4]), .S (n_67), .Y
       (n_86));
  MUX2X1 g2416__4733(.A (clk_div[5]), .B (write_data[5]), .S (n_67), .Y
       (n_85));
  MUX2X1 g2417__6161(.A (clk_div[6]), .B (write_data[6]), .S (n_67), .Y
       (n_84));
  INVX1 g2418(.A (n_80), .Y (n_83));
  INVX1 g2419(.A (n_79), .Y (n_82));
  INVX1 g2420(.A (n_78), .Y (n_81));
  MUX2X1 g2421__9315(.A (clk_div[8]), .B (write_data[0]), .S (n_54), .Y
       (n_80));
  MUX2X1 g2422__9945(.A (clk_div[10]), .B (write_data[2]), .S (n_54),
       .Y (n_79));
  MUX2X1 g2423__2883(.A (clk_div[9]), .B (write_data[1]), .S (n_54), .Y
       (n_78));
  INVX1 g2426(.A (n_72), .Y (n_77));
  INVX1 g2427(.A (n_71), .Y (n_76));
  INVX1 g2428(.A (n_70), .Y (n_75));
  INVX1 g2429(.A (n_69), .Y (n_74));
  INVX1 g2430(.A (n_68), .Y (n_73));
  MUX2X1 g2431__2346(.A (clk_div[13]), .B (write_data[5]), .S (n_54),
       .Y (n_72));
  MUX2X1 g2432__1666(.A (clk_div[12]), .B (write_data[4]), .S (n_54),
       .Y (n_71));
  MUX2X1 g2433__7410(.A (clk_div[11]), .B (write_data[3]), .S (n_54),
       .Y (n_70));
  MUX2X1 g2434__6417(.A (clk_div[14]), .B (write_data[6]), .S (n_54),
       .Y (n_69));
  MUX2X1 g2435__5477(.A (clk_div[15]), .B (write_data[7]), .S (n_54),
       .Y (n_68));
  MUX2X1 g2442__2398(.A (n_363), .B (n_5), .S (n_31), .Y (n_66));
  AND2X1 g2443__5107(.A (n_14), .B (n_64), .Y (n_65));
  OR2X1 g2448__6260(.A (n_1), .B (n_8), .Y (n_67));
  HAX1 g2449__4319(.A (u_clk_gen_counter[1]), .B
       (u_clk_gen_counter[0]), .YC (n_63), .YS (n_64));
  INVX1 g2462(.A (n_53), .Y (n_62));
  INVX1 g2463(.A (n_49), .Y (n_61));
  INVX1 g2464(.A (n_48), .Y (n_60));
  INVX1 g2465(.A (n_47), .Y (n_59));
  INVX1 g2466(.A (n_46), .Y (n_58));
  INVX1 g2467(.A (n_45), .Y (n_57));
  INVX1 g2468(.A (n_44), .Y (n_56));
  INVX1 g2469(.A (n_43), .Y (n_55));
  MUX2X1 g2470__8428(.A (tx_data[2]), .B (write_data[2]), .S (n_15), .Y
       (n_53));
  NOR2X1 g2471__5526(.A (n_16), .B (u_fsm_state[0]), .Y (n_52));
  NAND2X1 g2472__6783(.A (addr[1]), .B (n_35), .Y (n_51));
  OAI21X1 g2473__3680(.A (n_6), .B (n_13), .C (u_clk_gen_n_237), .Y
       (n_50));
  MUX2X1 g2474__1617(.A (tx_data[0]), .B (write_data[0]), .S (n_15), .Y
       (n_49));
  MUX2X1 g2475__2802(.A (tx_data[1]), .B (write_data[1]), .S (n_15), .Y
       (n_48));
  MUX2X1 g2476__1705(.A (tx_data[7]), .B (write_data[7]), .S (n_15), .Y
       (n_47));
  MUX2X1 g2477__5122(.A (tx_data[3]), .B (write_data[3]), .S (n_15), .Y
       (n_46));
  MUX2X1 g2478__8246(.A (tx_data[4]), .B (write_data[4]), .S (n_15), .Y
       (n_45));
  MUX2X1 g2479__7098(.A (tx_data[5]), .B (write_data[5]), .S (n_15), .Y
       (n_44));
  MUX2X1 g2480__6131(.A (tx_data[6]), .B (write_data[6]), .S (n_15), .Y
       (n_43));
  OR2X1 g2481__1881(.A (n_3), .B (n_8), .Y (n_54));
  INVX1 g2482(.A (n_38), .Y (n_42));
  INVX1 g2483(.A (n_34), .Y (n_41));
  INVX1 g2484(.A (n_33), .Y (n_40));
  INVX1 g2485(.A (n_32), .Y (n_39));
  MUX2X1 g2486__5115(.A (u_regs_reg_rx_data[0]), .B (rx_data[0]), .S
       (n_363), .Y (n_38));
  AND2X1 g2487__7482(.A (n_14), .B (n_4), .Y (n_37));
  NAND3X1 g2488__4733(.A (write_en), .B (addr[1]), .C (n_252), .Y
       (n_36));
  NOR3X1 g2489__6161(.A (addr[0]), .B (addr[2]), .C (n_9), .Y (n_35));
  MUX2X1 g2490__9315(.A (u_regs_reg_rx_data[3]), .B (rx_data[3]), .S
       (n_363), .Y (n_34));
  MUX2X1 g2491__9945(.A (u_regs_reg_rx_data[1]), .B (rx_data[1]), .S
       (n_363), .Y (n_33));
  MUX2X1 g2492__2883(.A (u_regs_reg_rx_data[2]), .B (rx_data[2]), .S
       (n_363), .Y (n_32));
  OR2X1 g2493__2346(.A (n_2), .B (start), .Y (n_31));
  INVX1 g2494(.A (n_23), .Y (n_30));
  INVX1 g2495(.A (n_22), .Y (n_29));
  INVX1 g2496(.A (n_21), .Y (n_28));
  INVX1 g2497(.A (n_20), .Y (n_27));
  INVX1 g2498(.A (n_19), .Y (n_26));
  INVX1 g2499(.A (n_18), .Y (n_25));
  INVX1 g2500(.A (n_17), .Y (n_24));
  MUX2X1 g2501__1666(.A (u_regs_reg_ctrl[0]), .B (write_data[0]), .S
       (n_362), .Y (n_23));
  MUX2X1 g2502__7410(.A (u_regs_reg_rx_data[5]), .B (rx_data[5]), .S
       (n_363), .Y (n_22));
  MUX2X1 g2503__6417(.A (u_regs_reg_rx_data[6]), .B (rx_data[6]), .S
       (n_363), .Y (n_21));
  MUX2X1 g2504__5477(.A (u_regs_reg_rx_data[7]), .B (rx_data[7]), .S
       (n_363), .Y (n_20));
  MUX2X1 g2505__2398(.A (u_regs_reg_rx_data[4]), .B (rx_data[4]), .S
       (n_363), .Y (n_19));
  MUX2X1 g2506__5107(.A (u_regs_reg_ctrl[1]), .B (write_data[1]), .S
       (n_362), .Y (n_18));
  MUX2X1 g2507__6260(.A (spi_mode[1]), .B (write_data[2]), .S (n_362),
       .Y (n_17));
  MUX2X1 g2508__4319(.A (bit_cnt_max), .B (start), .S (u_fsm_state[1]),
       .Y (n_16));
  OR2X1 g2510__8428(.A (n_360), .B (n_10), .Y (n_15));
  INVX1 g2511(.A (n_14), .Y (n_13));
  NAND2X1 g2512__5526(.A (n_363), .B (u_regs_n_142), .Y (n_12));
  AND2X1 g2513__6783(.A (u_clk_gen_n_76), .B (n_11), .Y (n_14));
  INVX1 g2533(.A (write_en), .Y (n_9));
  INVX1 drc_bufs2674(.A (u_clk_gen_counter[0]), .Y (n_4));
  INVX1 drc_bufs2678(.A (u_clk_gen_sclk_int), .Y (n_6));
  INVX1 drc_bufs2754(.A (u_regs_reg_done_latch), .Y (n_5));
  BUFX2 drc_bufs2756(.A (n_36), .Y (n_3));
  BUFX2 drc_bufs2757(.A (n_12), .Y (n_2));
  BUFX2 drc_bufs2758(.A (n_51), .Y (n_1));
  BUFX2 drc_bufs2759(.A (n_52), .Y (n_0));
  BUFX2 drc_bufs2760(.A (n_195), .Y (tx_data[0]));
  BUFX2 drc_bufs2761(.A (n_194), .Y (tx_data[1]));
  BUFX2 drc_bufs2762(.A (n_192), .Y (tx_data[3]));
  BUFX2 drc_bufs2763(.A (n_188), .Y (tx_data[7]));
  BUFX2 drc_bufs2764(.A (n_180), .Y (u_regs_reg_rx_data[1]));
  BUFX2 drc_bufs2765(.A (n_141), .Y (u_clk_gen_counter[0]));
  BUFX2 drc_bufs2766(.A (n_142), .Y (u_clk_gen_counter[1]));
  BUFX2 drc_bufs2767(.A (n_143), .Y (u_clk_gen_counter[2]));
  BUFX2 drc_bufs2768(.A (n_144), .Y (u_clk_gen_counter[3]));
  BUFX2 drc_bufs2769(.A (n_145), .Y (u_clk_gen_counter[4]));
  BUFX2 drc_bufs2770(.A (n_146), .Y (u_clk_gen_counter[5]));
  BUFX2 drc_bufs2771(.A (n_147), .Y (u_clk_gen_counter[6]));
  BUFX2 drc_bufs2772(.A (n_148), .Y (u_clk_gen_counter[7]));
  BUFX2 drc_bufs2773(.A (n_149), .Y (u_clk_gen_counter[8]));
  BUFX2 drc_bufs2774(.A (n_150), .Y (u_clk_gen_counter[9]));
  BUFX2 drc_bufs2775(.A (n_151), .Y (u_clk_gen_counter[10]));
  BUFX2 drc_bufs2776(.A (n_152), .Y (u_clk_gen_counter[11]));
  BUFX2 drc_bufs2777(.A (n_153), .Y (u_clk_gen_counter[12]));
  BUFX2 drc_bufs2778(.A (n_154), .Y (u_clk_gen_counter[13]));
  BUFX2 drc_bufs2779(.A (n_155), .Y (u_clk_gen_counter[14]));
  BUFX2 drc_bufs2780(.A (n_156), .Y (u_clk_gen_counter[15]));
  BUFX2 drc_bufs2781(.A (n_157), .Y (u_clk_gen_sclk_int));
  BUFX2 drc_bufs2782(.A (n_158), .Y (u_fsm_state[0]));
  BUFX2 drc_bufs2783(.A (n_159), .Y (clk_div[8]));
  BUFX2 drc_bufs2784(.A (n_160), .Y (clk_div[9]));
  BUFX2 drc_bufs2785(.A (n_161), .Y (clk_div[10]));
  BUFX2 drc_bufs2786(.A (n_164), .Y (clk_div[13]));
  BUFX2 drc_bufs2787(.A (n_163), .Y (clk_div[12]));
  BUFX2 drc_bufs2788(.A (n_179), .Y (u_regs_reg_rx_data[0]));
  BUFX2 drc_bufs2789(.A (n_165), .Y (clk_div[14]));
  BUFX2 drc_bufs2790(.A (n_166), .Y (clk_div[15]));
  BUFX2 drc_bufs2791(.A (n_167), .Y (clk_div[0]));
  BUFX2 drc_bufs2792(.A (n_168), .Y (clk_div[1]));
  BUFX2 drc_bufs2793(.A (n_169), .Y (clk_div[2]));
  BUFX2 drc_bufs2794(.A (n_170), .Y (clk_div[3]));
  BUFX2 drc_bufs2795(.A (n_171), .Y (clk_div[4]));
  BUFX2 drc_bufs2796(.A (n_172), .Y (clk_div[5]));
  BUFX2 drc_bufs2797(.A (n_173), .Y (clk_div[6]));
  BUFX2 drc_bufs2798(.A (n_174), .Y (clk_div[7]));
  BUFX2 drc_bufs2799(.A (n_175), .Y (u_regs_reg_ctrl[0]));
  BUFX2 drc_bufs2800(.A (n_176), .Y (u_regs_reg_ctrl[1]));
  BUFX2 drc_bufs2801(.A (n_177), .Y (spi_mode[1]));
  BUFX2 drc_bufs2802(.A (n_162), .Y (clk_div[11]));
  BUFX2 drc_bufs2803(.A (n_187), .Y (u_fsm_state[1]));
  BUFX2 drc_bufs2804(.A (n_178), .Y (u_regs_reg_done_latch));
  BUFX2 drc_bufs2805(.A (n_181), .Y (u_regs_reg_rx_data[2]));
  BUFX2 drc_bufs2806(.A (n_182), .Y (u_regs_reg_rx_data[3]));
  BUFX2 drc_bufs2807(.A (n_183), .Y (u_regs_reg_rx_data[4]));
  BUFX2 drc_bufs2808(.A (n_184), .Y (u_regs_reg_rx_data[5]));
  BUFX2 drc_bufs2809(.A (n_185), .Y (u_regs_reg_rx_data[6]));
  BUFX2 drc_bufs2810(.A (n_191), .Y (tx_data[4]));
  BUFX2 drc_bufs2811(.A (n_186), .Y (u_regs_reg_rx_data[7]));
  BUFX2 drc_bufs2812(.A (n_193), .Y (tx_data[2]));
  BUFX2 drc_bufs2813(.A (n_189), .Y (tx_data[6]));
  BUFX2 drc_bufs2814(.A (n_190), .Y (tx_data[5]));
  BUFX2 g4101(.A (n_351), .Y (load_en));
  OR2X1 g2(.A (n_391), .B (n_313), .Y (n_392));
  XNOR2X1 g3(.A (n_291), .B (n_289), .Y (n_391));
endmodule

